export APP_FULL_NAME="server";
export APP_NAMESPACE="master-thesis";
export QUIC_CONFIG_HANDSHAKE_IDLE_TIMEOUT_MS=1000
export QUIC_CONFIG_KEEP_ALIVE_PERIOD=1000
export QUIC_CONFIG_MAX_IDLE_TIMEOUT_MS=1000
export SERVER_CONFIG_HTTP3_SERVER_PORT=4219
export SERVER_CONFIG_HTTP3_SERVER_ADDRESS="0.0.0.0";
export IMAGE_CONFIG_IMAGE_DIRECTORY="./images";
export IMAGE_CONFIG_IMAGE_EXTENSION=".jpg";
export JSON_CONFIG_DIRECTORY="./json";
export MYSQL_CONFIG_USERNAME="";
export MYSQL_CONFIG_PASSWORD="";
export MYSQL_CONFIG_DATABASE_ADDRESS="";
export MYSQL_CONFIG_DATABASE_NAME="";
export MYSQL_CONFIG_DATABASE_PORT="";
export MYSQL_CONFIG_DATABASE_TABLE="";
export MYSQL_CONFIG_DATABASE_NAME="";
export EVENT_ID=0 DATABASE_ENABLED="FALSE";